name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install flake8 pytest pytest-cov
    
    - name: Lint with flake8
      run: flake8 app/ --max-line-length=120 --ignore=E501,W503
    
    - name: Run tests
      run: pytest -v
    
    - name: Build Docker image
      run: docker build -t market-data-service .
